default-resources:
    - cpus=1
    - mem_mb=8000
    - runtime=15
printshellcmds: True
use-singularity: True
singularity-args: " --cleanenv"
keep-going: True
rerun-incomplete: True
use-conda: True
conda-frontend: "conda"
